
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.data.ProxyMgr": "touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "touch/src/draw/engine/SvgContext.js",
  "Ext.force.Force": "packages/force/src/Force.js",
  "Ext.force.ForceProxy": "packages/force/src/ForceProxy.js",
  "Ext.force.ForceReader": "packages/force/src/ForceReader.js",
  "Ext.force.ForceWriter": "packages/force/src/ForceWriter.js",
  "mySFApp": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.force.Force": [],
  "Ext.force.ForceProxy": [],
  "Ext.force.ForceReader": [],
  "Ext.force.ForceWriter": [],
  "mySFApp.view.Main": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.force.Force": [],
  "Ext.force.ForceProxy": [
    "proxy.force"
  ],
  "Ext.force.ForceReader": [
    "reader.force"
  ],
  "Ext.force.ForceWriter": [
    "writer.force"
  ],
  "mySFApp.view.Main": [
    "widget.main"
  ]
});
